name: Update Documentation Site

on: workflow_dispatch

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Install docfx
        run: dotnet tool install -g docfx --version 2.70.1

      - name: Build
        run: docfx Docs/docfx.json

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: Docs/_site
          commit-message: Update site